# Generated by Django 3.0.8 on 2020-08-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('real_breed', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('address',)},
            },
        ),
    ]
